sudo: required
services:
  - docker

before_install:
  - docker build -t emile222/docker-react -f Dockerfile.dev .

script:
  - docker run emile222/docker-react npm run test -- --coverage

deploy:
  provoder: eleasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-913835799611"
  bucket_path: "docker-react"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
   secure: "AWS_SECRET_KEY"
